### ISSUE TITLE
Is it possible to make nghttpx(worked as a forwarded proxy) decide backend by the frontend domain names?

### ISSUE THREAD

**Issue by joeshae** [nghttp2/nghttp2#733] opened 2016-11-26 09:27 UTC
Hi tatsuhiro-t, is it possible to make nghttpx(worked as a forwarded proxy) decide backend by the frontend domain names?

We're using nghttpx as a forwarded proxy in front of squid.

We have three domain names for nghttpx frontend:
```
frontend=0.0.0.0,443

private-key-file=/usr/etc/certs/a.test.com.key
certificate-file=/usr/etc/certs/a.test.com.crt

subcert=/usr/etc/certs/b.test.com.key:/usr/etc/certs/b.test.com.crt
subcert=/usr/etc/certs/c.test.com.key:/usr/etc/certs/c.test.com.crt
```

And we have four different backends:
```
backend=127.0.0.1,10001
backend=127.0.0.1,10002
backend=127.0.0.1,10003
backend=127.0.0.1,10004
```

We want:
the connections via ```a.test.com```, ```*.a.test.com```, ```*.*.a.test.com```, ```*.*.*.a.test.com```, ...  are all redirected to 127.0.0.1:10001
the connections via **ONLY** ```b.test.com``` and ```*.b.test.com``` are all redirected to 127.0.0.1:10002
the connections via **ONLY** ```c.test.com``` are all redirected to 127.0.0.1:10003
all other connections are all redirected to 127.0.0.1:10004

But the current nghttpx can not do this when nghttpx worked as a forwarded proxy.
Could you please add this new feature? It's very important to us.
Thank you!

**Comment by devil0118** [comment] 2017-01-22 04:53
Where is the answer?

**Comment by tatsuhiro-t** [comment] 2017-01-22 05:17
Not decided yet.

**Comment by devil0118** [comment] 2017-01-22 05:48
@tatsuhiro-t Can you tell me the key file is which?I to change by myself

**Comment by tatsuhiro-t** [comment] 2017-01-22 10:20
https://github.com/nghttp2/nghttp2/blob/db938afd668be57c7a24710ea54063a89a953150/src/shrpx_config.cc#L3537

if http2_proxy is true, we disable routing feature.  But just changing this function does not work, especially for CONNECT method.  I don't recommend to do that at the moment, and will not answer any question for any consequences by changing that function.

**Comment by devil0118** [comment] 2017-01-23 02:03
Thank you!!!

**Comment by tatsuhiro-t** [comment] 2017-01-25 16:07
#788 implements backend pattern match with http2-proxy enabled.  Please test it.  If it works fine, we will consider to merge the PR, and include it in the next release.

**Comment by devil0118** [comment] 2017-01-26 07:47
Test success！！！After the Chinese New Year, our team will be more detailed testing

**Comment by tatsuhiro-t** [comment] 2017-01-26 11:39
Thank you.  Keep in touch with us.

**Comment by joeshae** [comment] 2017-03-04 18:51
@tatsuhiro-t Has this patch been included in v1.20.0? If not, do you have some schedules about this? Thank you!

**Comment by tatsuhiro-t** [comment] 2017-03-05 10:31
It has not been merged yet.  My plan is that after hearing the test result from @devil0118 , PR will get merged.  Have you tested this PR, and Did it work for you?

**Comment by devil0118** [comment] 2017-03-06 01:53
Yes,  my team has the tests pass, had not found the problem

**Comment by tatsuhiro-t** [comment] 2017-03-06 12:24
Merged.

**Comment by joeshae** [comment] 2017-04-16 11:12
@tatsuhiro-t , Sorry for the delayed reply.
Thank you very much for your update. But I think you might misunderstand what's my requirement.

I need the requests to the same nghttpx, which has multiple domain names, to be redirected to different backends by these domain names. No matter what the request is for.

That's to say, the nghttpx **itself** has multiple domain names, A.com & B.com. 
Requests from users, who connect to the nghttpx by the domain name A.com, are all redirect to backend 1.
Requests from users, who connect to the nghttpx by the domain name B.com, are all redirect to backend 2.
No matter what are the destinations of their requests, google.com, fb.com, twitter.com, it's not important.

The `PATTEN` in nghttpx configuration's `-b` should be applied to A.com, B.com ..., but not google.com, fb.com, twitter.com.

**Comment by tatsuhiro-t** [comment] 2017-04-16 12:36
Yes, I misunderstood the request.   You want SNI based forwarding.

**Comment by joeshae** [comment] 2017-04-16 12:50
@tatsuhiro-t This feature is very important to us. I really hope you could help us.
If you think it's improper to be added to the release versions, could you please provide a patch for us?
Thank you very much!

**Comment by tatsuhiro-t** [comment] 2017-04-16 13:38
I'll create a patch so that you can test it.  If it goes successful, I'll consider to merge it in the master branch.

**Comment by joeshae** [comment] 2017-04-16 14:16
OK! Thank you tatsuhiro-t!

**Comment by tatsuhiro-t** [comment] 2017-04-16 14:51
#892 implements this.  I'm not quite comfortable with the parameter name, but the feature itself is there.

**Comment by tatsuhiro-t** [comment] 2017-04-16 14:51
To enable SNI based forwarding, add `sni-fwd` parameter to --frontend option.

**Comment by joeshae** [comment] 2017-04-16 15:03
Excellent! I'll give you feedback ASAP.

**Comment by joeshae** [comment] 2017-04-16 15:55
Tested! This feature is exactly what we need!
No problem found until now!
Thank you @tatsuhiro-t !

**Comment by joeshae** [comment] 2017-04-16 16:10
I guess there might be some bugs in the patch.
If I change the connecting domain name which used by nghttpx many times at browser, nghttpx sometimes goes to select the default backend permanently, unless I kill the nghttpx process and start it again.

**Comment by tatsuhiro-t** [comment] 2017-04-17 15:03
I couldn't reproduce this.  As far as I know, when sni-fwd is used, HTTP method doesn't matter.
Info level log shows more useful information like so:

```
Perform mapping selection, using host=localhost, path=/
Found pattern with query /, matched pattern=/
```

If you are using nghttpx as HTTP/2 proxy (secure HTTP proxy), the browser connects to the proxy using the proxy domain.   I'm not sure what is the actual use case here.

**Comment by joeshae** [comment] 2017-04-17 15:42
In my case, nghttpx is used as HTTP/2 proxy frontend, and squid work as backend on the same server. And Chrome is configured by PAC to connect to nghttpx.
I'm doing more test now and I will provide more logs for further investigation.

**Comment by joeshae** [comment] 2017-04-17 15:56
I think it has no relation with the backend squid.

This is my nghttpx's configs:

```
server-name=test
daemon=yes
http2-proxy=yes
npn-list=h2
# npn-list=h2,h2-16,h2-14,http/1.1

private-key-file=/usr/etc/certs/a.com.key
certificate-file=/usr/etc/certs/a.com.crt

subcert=/usr/etc/certs/b.com.key:/usr/etc/certs/b.com.crt

frontend=0.0.0.0,443;sni-fwd

backend=127.0.0.1,25;*.a.com
backend=127.0.0.1,26;*.b.com
backend=127.0.0.1,30

workers=1
backlog=10240
fastopen=10240

frontend-http2-optimize-write-buffer-size=yes
listener-disable-timeout=0
backend-connections-per-host=1024
backend-connect-timeout=5s

api-max-request-body=256K
backend-connections-per-host=1024
request-header-field-buffer=256K
max-request-header-fields=1000
response-header-field-buffer=256K
max-response-header-fields=1000

add-x-forwarded-for=yes
no-via=yes

errorlog-file=/var/log/nghttpx/error-443.log

accesslog-file=/var/log/nghttpx/access-443.log
accesslog-format=[$time_local] $remote_addr:$remote_port->:$server_port->$backend_host:$backend_port $body_bytes_sent $request_time $status $pid $alpn $ssl_cipher $ssl_protocol $ssl_session_id $ssl_session_reused "$request" "$http_user_agent"
```

Squid works at port 25, 26 and 30.

And Chrome is configured to connect https://a.com
Then I browse the website ipip.net, I can see the following logs:

```
[17/Apr/2017:23:45:56 +0800] 101.87.98.196:58429->:443->127.0.0.1:30 2679 1.034 200 3146 h2 ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 - . "CONNECT af.opera.com:443 HTTP/2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 OPR/43.0.2442.991"
[17/Apr/2017:23:46:03 +0800] 101.87.98.196:58430->:443->127.0.0.1:25 0 0.191 302 3146 h2 ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 912378d88ef81a67836e29171bbdf3b7c5c6366dc7494e728ce1793938d3939b r "GET http://ipip.net/ HTTP/2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 OPR/43.0.2442.991"
[17/Apr/2017:23:46:03 +0800] 101.87.98.196:58430->:443->127.0.0.1:25 6466 0.265 200 3146 h2 ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 912378d88ef81a67836e29171bbdf3b7c5c6366dc7494e728ce1793938d3939b r "GET http://www.ipip.net/ HTTP/2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 OPR/43.0.2442.991"
[17/Apr/2017:23:46:04 +0800] 101.87.98.196:58430->:443->127.0.0.1:25 982 0.079 200 3146 h2 ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 912378d88ef81a67836e29171bbdf3b7c5c6366dc7494e728ce1793938d3939b r "GET http://www.ipip.net/favicon.ico HTTP/2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 OPR/43.0.2442.991"
[17/Apr/2017:23:46:15 +0800] 101.87.98.196:58430->:443->127.0.0.1:25 6466 0.121 200 3146 h2 ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 912378d88ef81a67836e29171bbdf3b7c5c6366dc7494e728ce1793938d3939b r "GET http://www.ipip.net/ HTTP/2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 OPR/43.0.2442.991"
[17/Apr/2017:23:46:16 +0800] 101.87.98.196:58430->:443->127.0.0.1:25 5708 0.410 200 3146 h2 ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 912378d88ef81a67836e29171bbdf3b7c5c6366dc7494e728ce1793938d3939b r "GET http://www.ipip.net/ip.html HTTP/2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 OPR/43.0.2442.991"
[17/Apr/2017:23:46:16 +0800] 101.87.98.196:58430->:443->127.0.0.1:30 6920 0.054 200 3146 h2 ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 912378d88ef81a67836e29171bbdf3b7c5c6366dc7494e728ce1793938d3939b r "CONNECT trace.rtbasia.com:443 HTTP/2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 OPR/43.0.2442.991"
[17/Apr/2017:23:46:16 +0800] 101.87.98.196:58430->:443->127.0.0.1:25 32 0.001 200 3146 h2 ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 912378d88ef81a67836e29171bbdf3b7c5c6366dc7494e728ce1793938d3939b r "GET http://trace.rtbasia.com/tkj?rta_k=8QUnu0qsgQ&rta_sr=1440x900&rta_page=http%3A%2F%2Fwww.ipip.net%2Fip.html&rta_rf=http%3A%2F%2Fwww.ipip.net%2F&callback=RTB_7611492443976566 HTTP/2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 OPR/43.0.2442.991"
[17/Apr/2017:23:46:16 +0800] 101.87.98.196:58430->:443->127.0.0.1:30 405 0.022 200 3146 h2 ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 912378d88ef81a67836e29171bbdf3b7c5c6366dc7494e728ce1793938d3939b r "CONNECT trace.rtbasia.com:443 HTTP/2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 OPR/43.0.2442.991"
[17/Apr/2017:23:46:16 +0800] 101.87.98.196:58430->:443->127.0.0.1:25 76 0.072 200 3146 h2 ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 912378d88ef81a67836e29171bbdf3b7c5c6366dc7494e728ce1793938d3939b r "GET http://googleads.g.doubleclick.net/pagead/viewthroughconversion/988136862/?random=1492443976561&cv=8&fst=1492443976561&num=1&fmt=1&label=Ta68CLr_8V8QnouX1wM&guid=ON&u_h=900&u_w=1440&u_ah=877&u_aw=1399&u_cd=24&u_his=3&u_tz=480&u_java=false&u_nplug=5&u_nmime=7&frm=0&url=http%3A%2F%2Fwww.ipip.net%2Fip.html&ref=http%3A%2F%2Fwww.ipip.net%2F&tiba=IP%E6%9F%A5%E8%AF%A2_%E6%9C%80%E4%B8%93%E4%B8%9A%E7%9A%84%20IP%20%E5%9C%B0%E5%9D%80%E5%BA%93_IPIP.NET HTTP/2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 OPR/43.0.2442.991"
[17/Apr/2017:23:46:18 +0800] 101.87.98.196:58430->:443->127.0.0.1:25 126 1.982 200 3146 h2 ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 912378d88ef81a67836e29171bbdf3b7c5c6366dc7494e728ce1793938d3939b r "POST http://www.ipip.net/ip/ajax/ HTTP/2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 OPR/43.0.2442.991"
[17/Apr/2017:23:46:20 +0800] 101.87.98.196:58430->:443->127.0.0.1:25 20 0.116 200 3146 h2 ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 912378d88ef81a67836e29171bbdf3b7c5c6366dc7494e728ce1793938d3939b r "POST http://www.ipip.net/ip/ajax/ HTTP/2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 OPR/43.0.2442.991"
[17/Apr/2017:23:46:23 +0800] 101.87.98.196:58430->:443->127.0.0.1:25 5075 0.081 200 3146 h2 ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 912378d88ef81a67836e29171bbdf3b7c5c6366dc7494e728ce1793938d3939b r "GET http://www.ipip.net/download.html HTTP/2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 OPR/43.0.2442.991"
[17/Apr/2017:23:46:02 +0800] 101.87.98.196:58430->:443->127.0.0.1:30 4505 22.646 200 3146 h2 ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 912378d88ef81a67836e29171bbdf3b7c5c6366dc7494e728ce1793938d3939b r "CONNECT speeddials.opera.com:443 HTTP/2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 OPR/43.0.2442.991"
[17/Apr/2017:23:45:58 +0800] 101.87.98.196:58430->:443->127.0.0.1:30 3031 61.231 200 3146 h2 ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 912378d88ef81a67836e29171bbdf3b7c5c6366dc7494e728ce1793938d3939b r "CONNECT af.opera.com:443 HTTP/2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 OPR/43.0.2442.991"
[17/Apr/2017:23:46:02 +0800] 101.87.98.196:58430->:443->-:- 132 60.002 504 3146 h2 ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 912378d88ef81a67836e29171bbdf3b7c5c6366dc7494e728ce1793938d3939b r "CONNECT www.google.com.hk:443 HTTP/2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 OPR/43.0.2442.991"
[17/Apr/2017:23:46:02 +0800] 101.87.98.196:58430->:443->-:- 132 60.000 504 3146 h2 ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 912378d88ef81a67836e29171bbdf3b7c5c6366dc7494e728ce1793938d3939b r "CONNECT www.google.com.hk:443 HTTP/2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 OPR/43.0.2442.991"
[17/Apr/2017:23:46:02 +0800] 101.87.98.196:58430->:443->127.0.0.1:30 3633 59.755 503 3146 h2 ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 912378d88ef81a67836e29171bbdf3b7c5c6366dc7494e728ce1793938d3939b r "CONNECT www.google.com.hk:443 HTTP/2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 OPR/43.0.2442.991"
[17/Apr/2017:23:46:02 +0800] 101.87.98.196:58430->:443->127.0.0.1:30 3633 59.655 503 3146 h2 ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 912378d88ef81a67836e29171bbdf3b7c5c6366dc7494e728ce1793938d3939b r "CONNECT www.google.com.hk:443 HTTP/2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 OPR/43.0.2442.991"
[17/Apr/2017:23:46:02 +0800] 101.87.98.196:58430->:443->127.0.0.1:30 3633 59.455 503 3146 h2 ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 912378d88ef81a67836e29171bbdf3b7c5c6366dc7494e728ce1793938d3939b r "CONNECT www.google.com.hk:443 HTTP/2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 OPR/43.0.2442.991"
[17/Apr/2017:23:46:02 +0800] 101.87.98.196:58430->:443->127.0.0.1:30 3633 59.295 503 3146 h2 ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 912378d88ef81a67836e29171bbdf3b7c5c6366dc7494e728ce1793938d3939b r "CONNECT www.google.com.hk:443 HTTP/2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 OPR/43.0.2442.991"
[17/Apr/2017:23:46:04 +0800] 101.87.98.196:58430->:443->127.0.0.1:30 85006 60.318 200 3146 h2 ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 912378d88ef81a67836e29171bbdf3b7c5c6366dc7494e728ce1793938d3939b r "CONNECT cdn.ipip.net:443 HTTP/2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 OPR/43.0.2442.991"
[17/Apr/2017:23:46:03 +0800] 101.87.98.196:58430->:443->127.0.0.1:30 126975 60.749 200 3146 h2 ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 912378d88ef81a67836e29171bbdf3b7c5c6366dc7494e728ce1793938d3939b r "CONNECT cdn.ipip.net:443 HTTP/2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 OPR/43.0.2442.991"
[17/Apr/2017:23:46:03 +0800] 101.87.98.196:58430->:443->127.0.0.1:30 101617 60.749 200 3146 h2 ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 912378d88ef81a67836e29171bbdf3b7c5c6366dc7494e728ce1793938d3939b r "CONNECT cdn.ipip.net:443 HTTP/2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 OPR/43.0.2442.991"
[17/Apr/2017:23:46:04 +0800] 101.87.98.196:58430->:443->127.0.0.1:30 112780 60.326 200 3146 h2 ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 912378d88ef81a67836e29171bbdf3b7c5c6366dc7494e728ce1793938d3939b r "CONNECT cdn.ipip.net:443 HTTP/2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 OPR/43.0.2442.991"
[17/Apr/2017:23:46:04 +0800] 101.87.98.196:58430->:443->127.0.0.1:30 91326 60.733 200 3146 h2 ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 912378d88ef81a67836e29171bbdf3b7c5c6366dc7494e728ce1793938d3939b r "CONNECT cdn.ipip.net:443 HTTP/2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 OPR/43.0.2442.991"
[17/Apr/2017:23:46:04 +0800] 101.87.98.196:58430->:443->127.0.0.1:30 185663 72.051 200 3146 h2 ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 912378d88ef81a67836e29171bbdf3b7c5c6366dc7494e728ce1793938d3939b r "CONNECT cdn.ipip.net:443 HTTP/2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 OPR/43.0.2442.991"
[17/Apr/2017:23:46:16 +0800] 101.87.98.196:58430->:443->127.0.0.1:30 4973 60.067 200 3146 h2 ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 912378d88ef81a67836e29171bbdf3b7c5c6366dc7494e728ce1793938d3939b r "CONNECT ip.rtbasia.com:443 HTTP/2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 OPR/43.0.2442.991"
[17/Apr/2017:23:46:16 +0800] 101.87.98.196:58430->:443->127.0.0.1:30 9808 60.142 200 3146 h2 ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 912378d88ef81a67836e29171bbdf3b7c5c6366dc7494e728ce1793938d3939b r "CONNECT www.googleadservices.com:443 HTTP/2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 OPR/43.0.2442.991"
[17/Apr/2017:23:46:16 +0800] 101.87.98.196:58430->:443->127.0.0.1:30 5348 60.161 200 3146 h2 ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 912378d88ef81a67836e29171bbdf3b7c5c6366dc7494e728ce1793938d3939b r "CONNECT ip.rtbasia.com:443 HTTP/2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 OPR/43.0.2442.991"
[17/Apr/2017:23:46:04 +0800] 101.87.98.196:58430->:443->127.0.0.1:30 18035 79.209 200 3146 h2 ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 912378d88ef81a67836e29171bbdf3b7c5c6366dc7494e728ce1793938d3939b r "CONNECT www.google-analytics.com:443 HTTP/2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 OPR/43.0.2442.991"
```

All requests should be forwarded to 127.0.0.1:25.
But the requests using CONNECT doesn't work as expected, which are forwarded to the default backend 127.0.0.1:30.

**Comment by tatsuhiro-t** [comment] 2017-04-18 11:04
Thank you.  I identified the bug.  Will fix soon.

**Comment by tatsuhiro-t** [comment] 2017-04-18 12:29
The bug has been fixed in master branch.

**Comment by joeshae** [comment] 2017-04-18 12:33
Thank you @tatsuhiro-t very much! It's very kind of you!
It works fine now!

**Closed** 2017-04-19 12:22 UTC
Labels: enhancement, nghttpx
