### ISSUE TITLE
RST_STREAM all pending push promises

### ISSUE THREAD

**Issue by rodrigobdz** [nghttp2/nghttp2#705] opened 2016-10-10 19:26 UTC
I'm using nghttpx client side to communicate with a server. I would like the proxy to RST_STREAM all pending push promises from previous requests but still push content for the current request.
The idea behind this is to save bandwidth by skipping the pending push promises from last requests.

I know from #689 that I have to call `nghttp2_submit_rst_stream`.
In #675 a snippet is shown about how to get all push promises but it is incomplete and is not clear enough to me.

**How do I get all pending push promises from previous requests?**

**Comment by tatsuhiro-t** [comment] 2016-10-11 12:10
duplicate of #689

**Closed by tatsuhiro-t** 2016-10-11 12:10 UTC
