### ISSUE TITLE
nghttpx  route request to different backend according to request host and path not work

### ISSUE THREAD

**Issue by devil0118** [nghttp2/nghttp2#786] opened 2017-01-22 01:30 UTC
nghttp2 1.18.1
nghttpx.conf
http2-proxy=yes
frontend=0.0.0.0,780;no-tls
backend=imququ.com,443;imququ.com;proto=h2;tls
backend=nghttp2.org,443;nghttp2.org;proto=h2;tls
backend=www.taobao.com,443;www.taobao.com;proto=h2;tls
no-ocsp=yes
npn-list=h2
insecure=yes
accesslog-format=$remote_addr - - [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$backend_host" "$backend_port"

accesslog-file=/home/parallels/Desktop/access.log

![image](https://cloud.githubusercontent.com/assets/4556669/22179131/48179030-e085-11e6-8570-e5ce0d3578f3.png)

![image](https://cloud.githubusercontent.com/assets/4556669/22179215/487f9c36-e088-11e6-9bcf-bfab65dd4802.png)

ths

**Comment by tatsuhiro-t** [comment] 2017-01-22 03:36
duplicate of #733

**Closed by tatsuhiro-t** 2017-01-22 03:36 UTC
