### ISSUE TITLE
Could you please explain me the behaviour of the following three different type of session errors ?

### ISSUE THREAD

**Issue by rameshrajagopal** [nghttp2/nghttp2#499] opened 2016-02-05 19:10 UTC
I am trying to understand the timeouts provided by nghttp2 api both on the client side and server side. I am seeing different behaviour, would like to understand more on this. 

1) When I set my conn_timeout and read_timeout by 2 secs, After 2 seconds, I am getting session connect timeout error through session error callback. Then immediately I am also getting session_connect callback with success message. Why is this behaviour ? Is the session still valid on this case ? 

2) I also do get "EndOfFile" error on session error callback. What does this mean ? After this error, all my submit_request() is failing with "unknown error", sess.submit() returns "nullptr". During this time, on the server side, the readtimeout is 2 seconds. What happened to the underlying session ? is it still valid ?

3) Could you point me the document to explain about these timeouts ? client side conn_timeout and read_timeout and server side read_timeout ? I am trying to find out how these timeout works, how can i use it properly ?

**Comment by tatsuhiro-t** [comment] 2016-02-06 02:12
> 1) When I set my conn_timeout and read_timeout by 2 secs, After 2 seconds, I am getting session connect timeout error through session error callback. Then immediately I am also getting session_connect callback with success message. Why is this behaviour ? Is the session still valid on this case ?

I found connect timeout did not work in client session.  It was fixed in 95ca4f55d5cf5022843ccb77a46cdbe5c40aed82.  I've not reproduced your issue, but I patched the code where I think it might happen, which is also included in that commit.

> 2) I also do get "EndOfFile" error on session error callback. What does this mean ? After this error, all my submit_request() is failing with "unknown error", sess.submit() returns "nullptr". During this time, on the server side, the readtimeout is 2 seconds. What happened to the underlying session ? is it still valid ?

"End of file" error means server dropped connection.  After that, session cannot be used.

> 3) Could you point me the document to explain about these timeouts ? client side conn_timeout and read_timeout and server side read_timeout ? I am trying to find out how these timeout works, how can i use it properly ?

See header file.  asio_http2_client.h and asio_http2_server.h.

**Comment by rameshrajagopal** [comment] 2016-02-06 16:19
Regarding read_timeout on the client session, So when does read timeout happen in the session ? Is this basically saying after you submitted the request to the server, it waits for "read_timeout" and returns is that so ? Should this error come via session error cb or req close cb with an timeout error code ?

**Comment by rameshrajagopal** [comment] 2016-02-06 16:22
I don't see much explanation on the .h file, on the server side, read_timeout, server waits for the response upto "read_timeout", if server doesn't receive response within this time, it cancels the request with time out error ?

**Comment by tatsuhiro-t** [comment] 2016-02-06 16:23
The read timeout is not related to request at all.  It is timeout for reading bytes from network.

**Comment by tatsuhiro-t** [comment] 2016-02-06 16:25
If you are looking for per stream timeout, we don't have that one at the moment.
And if you want them, please create new thread.

**Comment by tatsuhiro-t** [comment] 2024-03-23 06:30
Closed since asio library has been removed.

**Closed by tatsuhiro-t** 2024-03-23 06:30 UTC
Labels: bug, fix committed
